name: Format

on: [pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "17"
      - uses: axel-op/googlejavaformat-action@v3.0.0
        with:
          args: "--replace"
